<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BarCode" Version="2025.4.2" />
    <PackageReference Include="BarCode.Slim" Version="2025.4.2" />
    <PackageReference Include="CsvHelper" Version="33.0.1" />
    <PackageReference Include="hidlibrary" Version="3.3.40" />
    <PackageReference Include="IronSoftware.Native.PdfModel" Version="2025.4.16" />
    <PackageReference Include="IronSoftware.System.Drawing" Version="2025.3.6" />
  </ItemGroup>

</Project>
